#!/usr/bin/env bash
test -f .config
hasCfg=$?
if [ $hasCfg -eq 0 ]; then
	mv .config kernel
fi
cd kernel
if [ $hasCfg -eq 1 ]; then
	make defconfig
fi
make oldconfig
make -j$(nproc)
code=$?
mv .config ..
cd ..
exit $code
