name: build Grad Linux™

on:
    pull_request:
        branches: main
    push:
        branches: main

permissions:
    packages: write
    contents: read

env:
    PUSHERS: '["RixInGithub"]'
    REG: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
    build:
        name: build everything
        runs-on: ubuntu-latest
        container: ghcr.io/gradnux/builder:latest
        steps:
            - name: check out
              uses: actions/checkout@v5
              with:
                  lfs: true
            - name: install prerequisites
              run: |
                  # kernel
                  sudo apt install -y ccache flex bison libncurses-dev libssl-dev libelf-dev
                  # aria2c
                  # sudo apt install -y libxml2-dev autoconf automake autotools-dev autopoint libtool libssl-dev zlib1g-dev libsqlite3-dev libxml2-dev liblzma-dev libssl3
            - name: setup ccache
              uses: actions/cache@v5
              with:
                  path: |
                      kernel
                      .git/modules/kernel
                  key: build-ccache-${{ runner.os }}
                  restore-keys: build-ccache-${{ runner.os }}
            - name: setup
              run: |
                  cd rootfs
                  mkdir -p dev etc lib lib64 proc sbin sys usr tmp bin lib/tcc usr/local
                  cd ..
                  mkdir -p busybox ~/bb make gcc/source gcc/build rust
                  aria2c -j 16 -x 16 -s 16 "https://busybox.net/downloads/busybox-1.38.0.tar.bz2" -o bb.tar.bz2
                  tar -xf bb.tar.bz2 -C busybox --strip-components=1
                  tar -xf rust.tar.gz -C rust --strip-components=1
                  tar -xf make.tar.gz -C make --strip-components=1
                  git config --global --add safe.directory '*'
                  git submodule init
                  git submodule update --init --depth 1 kernel
                  git submodule update --init --recursive
            - name: build kernel (stub)
              run: |
                  ccache --max-size 10G
                  # CC="ccache gcc" HOSTCC="ccache gcc" ./buildKernel
                  # not now apparently
                  # let's not waste microsoft's resources (for now... heh heh...)
            - name: obtain musl
              run: cp -r /musl/. rootfs/usr
            - name: obtain rust
              run: |
                  cd rust
                  ./install.sh --destdir="$(realpath ../rootfs)" --without=rust-docs,rust-docs-json-preview
                  cd ..
                  rm -rf rust
                  # fuck you rust
            - name: build busybox
              run: |
                  ./setupBb
                  cd busybox
                  make oldconfig
                  MUSLCC="/musl/gcc -static --sysroot=/musl"
                  CC="$MUSLCC" CFLAGS="-static" LDFLAGS="-static" make -j$(nproc)
                  make CONFIG_PREFIX="$HOME/bb" install
                  mkdir -p ../rootfs/usr/share/man/man1/
                  cp docs/busybox.1 ../rootfs/usr/share/man/man1/busybox.1
                  cd ..
                  # "You will probably need to make your busybox binary setuid root to ensure all configured applets will work properly."
                  sudo chown root ~/bb/bin/busybox
                  sudo chmod 4755 ~/bb/bin/busybox
                  cp -a ~/bb/bin/busybox rootfs/bin/
                  for a in $(find ~/bb -type l -printf "%f " | sed "s/ *$//"); do
                      ln -sT busybox "rootfs/bin/$a"
                  done
            - name: build make ig
              run: |
                  cd make
                  MUSLCC="/musl/gcc -static"
                  CC="$MUSLCC" ./configure --host=x86_64-linux-gnu --build=x86_64-linux-musl --disable-dependency-tracking
                  CC="$MUSLCC" make -j$(nproc)
                  make install DESTDIR="$(realpath ../rootfs)"
                  cd ..
            - name: build final image?
              run: |
                  tree rootfs -I "tmp"
                  cd rootfs
                  chmod 1777 tmp
                  for a in bin lib; do
                      cp -r usr/"$a"/. "$a"
                      rm -rf usr/"$a"
                      ln -sT ../../"$a" usr/"$a"
                  done
                  cd ..
                  docker build -t "${{ github.event.repository.name }}:latest" -f Containerfile .
                  docker save -o gradnux.tar "${{ github.event.repository.name }}:latest"
            - name: upload state
              uses: actions/upload-artifact@v5
              with:
                  name: img
                  path: "${{ github.event.repository.name }}.tar"
            - name: login to ghcr
              uses: docker/login-action@v4
              if: github.event_name == 'push' && contains(fromJSON(env.PUSHERS), github.actor)
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: push to ghcr
              if: github.event_name == 'push' && contains(fromJSON(env.PUSHERS), github.actor)
              run: |
                  docker tag gradnux:latest "$REG:latest"
                  docker push "$REG:latest"
