name: build Grad Linux™

on: push

jobs:
    build:
        name: build the image ig
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
            - name: install prerequisites
              run: |
                  sudo apt update -y
                  # host helpers
                  sudo apt install -y build-essential gcc aria2
                  # kernel
                  sudo apt install -y ccache build-essential flex bison libncurses-dev libssl-dev libelf-dev
            - name: setup ccache
              uses: actions/cache@v4
              with:
                  path: ./kernel
                  key: kernel-ccache
                  restore-keys: kernel-ccache
            - name: build kernel
              run: |
                  ccache --max-size 10G
                  git submodule update --init --recursive --depth 1
                  # CC="ccache gcc" HOSTCC="ccache gcc" ./buildKernel
                  # not now apparently
            - name: attempt?
              run: |
                  mkdir -p musl rootfs/opt
                  aria2c -j 16 -x 16 -s 16 "https://musl.libc.org/releases/musl-1.2.2.tar.gz" -o musl.tar.gz
                  file musl.tar.gz
                  tar -xf musl.tar.gz -C musl --strip-components=1
                  cd musl
                  ls
                  CC=gcc AR=ar RANLIB=ranlib ./configure --prefix=/opt/musl --target=x86_64-linux-musl
                  make -j$(nproc)
                  make install
                  cd ..
                  cp -r /opt/musl/* rootfs/opt
                  echo "/opt/musl/bin/" >> $GITHUB_PATH
                  cd tcc
                  CC=musl-gcc ./configure --prefix="$HOME/tcc"
                  make tcc
                  make install
                  cd ..
                  cp -r ~/tcc/* rootfs/opt
                  tree rootfs
                  tree "$HOME/tcc"
                  podman build -t gradnux:latest .
                  podman save -o gradnux.tar gradnux:latest
            - name: upload image
              uses: actions/upload-artifact@v4
              with:
                  name: gradnuxImg
                  path: ./gradnux.tar