name: build Grad Linux™

on: push

jobs:
    build:
        name: build the image ig
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
            - name: install prerequisites
              run: |
                  sudo apt update -y
                  # bootc?
                  sudo apt install -y podman
                  # kernel
                  sudo apt install -y ccache build-essential flex bison libncurses-dev libssl-dev
            - name: setup ccache
              uses: actions/cache@v4
              with:
                  path: ~/ccache
                  key: kernel-ccache
                  restore-keys: kernel-ccache
            - name: build kernel
              run: |
                  ccache --max-size 10G
                  git submodule update --init --recursive
                  CC="ccache gcc" HOSTCC="ccache gcc" ./buildKernel
            - name: attempt?
              run: |
                  podman build -t gradnux:latest -f Containerfile .
                  # idfk